################################################################################
#  PLOT GENERATOR 
#  WARNING: ASSUMES CreditPricer main.jl HAS BEEN EXCUTED TO CALCULATE MTMS
#  AND CS01s ETC 

# Instructions: 
# - set working directory to the location of this code file 
# - execute relevant section to generate required plot 

source('data_pre_processing_index.R')
source('data_pre_processing_option.R')
source('plotting.R')


################################################################################
# PLOT INDEX MARKET SPREADS 
in_path <- './../../data/index_data.csv'
plot_index_spreads(in_path)

################################################################################
# PLOT INDEX STUDENT-T DISTRIBUTION FIT 
in_path <- './../../data/xo_otr_minus_1.csv'
plot_t_distribution_fit_to_returns(in_path)


################################################################################
# PLOT OPTION MARKET SMILES 
in_path <- './../../data/option_data.csv'
plot_all_smiles(in_path)


################################################################################
# PLOT OPTION 3D SURFACES OF PRICED CONTRACTS (NON-LINEARITY DEPICTION)

# assumes option_contracts_priced.csv already generated by CreditPricer code 
in_path <- './../../data/option_priced.csv'
out_path_scatter <- './../../plots/pricing_option_surfaces_scatter.png'
out_path_surface <- './../../plots/pricing_option_surfaces_surface.png'
#plot_option_3d_priced_surfaces_scatter(opt_config, in_path, out_path_scatter)
plot_option_3d_priced_surface(list(), in_path, out_path_surface, 'Payer')
plot_option_3d_priced_surface(list(), in_path, out_path_surface, 'Receiver')


################################################################################
# PLOT INDEX CURVES SELCTION (NON-LINEARITY DEPICTION)
# TODO 



